### ISSUE TITLE
Can't create issues after icinga-php-library upgrade to 0.11.0

### ISSUE THREAD

**Issue by dlmwcmp** [Icinga/icingaweb2-module-jira#104]
After upgrading the icingaweb2 backend to 2.13.4 and icinga-php-library simultaneously being upgraded to 0.11.0, it seems the Jira issue creation functionality has broken internally on the Icinga webnode end somehow. Error message we receive when pressing "JIRA issues" > "Create" in the webGUI:

`[Error](https://icinga.mgmt.nu/icingaweb2/jira/issues/create?host=c1001-0372)
 
Uncaught Error: Call to undefined method ipl\Html\FormElement\SelectElement::hasBeenValidatedAndIsNotValid() in /usr/share/icingaweb2/modules/jira/library/Jira/Web/Form/LegacyDecorator.php:105
Stack trace:
#0 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(294): Icinga\Module\Jira\Web\Form\LegacyDecorator->assemble()
#1 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(514): ipl\Html\HtmlDocument->ensureAssembled()
#2 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(430): ipl\Html\HtmlDocument->render()
#3 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(408): ipl\Html\HtmlDocument->renderWrappedDocument(Object(ipl\Html\FormElement\SelectElement))
#4 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(518): ipl\Html\HtmlDocument->renderWrapped()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument-

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}`

I understand there's a Jira module 1.3.0 just around the corner that may or may not have accounted for icinga-php-library 0.11.0, but still reporting the issue since it is an issue with the module :) 

Workaround suggestions welcomed

**Comment by nilmerg** [comment]
That should be solved by upgrading to v1.3.x
