### ISSUE TITLE
Cannot select (workflow) template while creating jira issue in 1.3.0

### ISSUE THREAD

**Issue by rafi0101** [Icinga/icingaweb2-module-jira#107]
Hello,

in the new 1.3.0 Version I cannot select a workflow template for a new jira issue.
After choosing a template I get the following error in Icingaweb: 
`ERROR: array_key_exists(): The first argument should be either a string or an integer`
This worked fine in v1.2.2

This is my configuration:
config.ini
```ini 
[api]
host = "secret"
username = "secret"
password = "secret"

[ui]
default_project = "secret"
default_issuetype = "Task"

[icingaweb]
url = "secret"
```

templates.ini
```ini
[ack]
components.0.name = "secret"
assignee.accountId = "secret"
labels.0 = "icinga"
```

Jira Module: 1.3.0
icinga-php-library: 0.11.0

**Comment by nilmerg** [comment]
Hi,

> ERROR: array_key_exists(): The first argument should be either a string or an integer

There should be a stacktrace involved, pleas show this.

In addition, please tell us your PHP version, or better yet, a screenshot of Icinga Web's about page.

**Comment by rafi0101** [comment]
No I cannot find any stacktrace just this error message.  

![image](https://user-images.githubusercontent.com/43086854/231167724-ef3d8c0f-e830-46de-99ce-17b962215ed5.png)
![image](https://user-images.githubusercontent.com/43086854/231167744-e69d0783-8a85-41b5-9eeb-96bb023f7b4f.png)

**Comment by rafi0101** [comment]
Icingaweb logs to syslog, but I can't see any error messages there either

**Comment by nilmerg** [comment]
Okay, thanks, we'll check whether we can reproduce this.

**Comment by raviks789** [comment]
@rafi0101 could you also mention the field types of fields used in your `ack` template.

**Comment by rafi0101** [comment]
These 3 fields are all "systemfields" so no custom fields. May if it helps my project is a company managed softwareproject

**Comment by rafi0101** [comment]
Hi @raviks789,
I have seen that you have fixed the problem. When do you think this will be released because I see it was finished 3 weeks ago?

**Comment by rafi0101** [comment]
Hi @nilmerg,
now it is already the middle of the next month. Any news?
