### ISSUE TITLE
Refresh issue when state changes

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-jira#14]
In case an issue already exists while it's state changed (like from warning to critical), the `icingaStatus` key should be refreshed and a comment with the current check output should be added.

**Comment by arcadesolutions** [comment]
Would this also include a transition back to an 'OK' or 'UP' state, maybe with an option to comment and close the issue?

**Comment by Thomas-Gelf** [comment]
Comments will be added for state changes, issues will not be closed. Most people I talked to where against doing so. @arcadesolutions: if you're still interested in the "close" part, please open a dedicated feature request - we could eventually introduce a dedicated flag allowing you to do so.
