### ISSUE TITLE
Error on Issue Link in Jira Issues

### ISSUE THREAD

**Issue by ChristianMoritz** [Icinga/icingaweb2-module-jira#18]
inside the Overview from a Ticket Serch Summary.
Ive got the Problem, that the Link which is pointing to the JIRA Issue is not properly formated.
there is one "7" to much.
Like:
https://jira.company.com//browse/IT-0123456

So the "//" before the browse is my Problem..

Could it be that inside the 
icingaweb2-module-jira/library/Jira/Web/Table/IssueDetails.php

there is a mistake ? 
in the config file there is no Slash inside, which can create this issue

My Enviroment:
Icinga2: r2.10.5-1
Director: 1.6.2
Jira - master

**Comment by Thomas-Gelf** [comment]
Will be fixed, this affects those who're running JIRA in their web servers document root.
