### ISSUE TITLE
how to disable ssl in the config?

### ISSUE THREAD

**Issue by loeken** [Icinga/icingaweb2-module-jira#19]
how to disable ssl in the config.ini

**Comment by Thomas-Gelf** [comment]
That's a damn good question, `https://` is currently hard-coded in the sources. Wasn't aware that plaintext is still a thing ;-)

Just kidding, I'll introduce and document a related config flag.

**Comment by Thomas-Gelf** [comment]
`scheme` is now available in the [configuration](https://github.com/Icinga/icingaweb2-module-jira/blob/master/doc/03-Configuration.md#configuration)
