### ISSUE TITLE
Documentation of Jira->Configuration page

### ISSUE THREAD

**Issue by jprusch** [Icinga/icingaweb2-module-jira#2]
Took me some time to figure out the function of the Jira Configuration page. Am I right it's just a hint of available projects, issue types & custom fields?

**Comment by Thomas-Gelf** [comment]
That's correct, it's useless right now - I should better remove it from the menu. Original idea was to add a web-based guided configuration, but there wasn't enough time for that.

**Comment by Thomas-Gelf** [comment]
Fixed with 0e93cf8
