### ISSUE TITLE
Jira module creates 3 tickets instead of 1

### ISSUE THREAD

**Issue by ChristianMoritz** [Icinga/icingaweb2-module-jira#20]
ive got a problem,
when a host is down (like in my test) the module creates 3 independent tickets instead of only 1.

is this a bug in the jira rest api or a bug insight the jira module from icinga ?

my enviroment:

icingaweb2: 2.7.1
php: 7.0.33-0
os: ubuntu16.04.6
director: 1.6.2
jira module (master) (git 22001dadf773a4baa299396da952053573d85d82)

**Comment by ChristianMoritz** [comment]
hy thomas,

the 2 custom fields (icingakeys & icingastatus) in jira are created.
(without the keys created you'll get an error in the jira module from icinga.)

and all the 3 tickets are created directly for the HOST, not for a specifiy Service from the Host.
see the screenshot ive posted in the icinga community forum
https://community.icinga.com/t/jira-module-creates-3-tickets-instead-of-one/2345

**Comment by ChristianMoritz** [comment]
meanwhile ive upgraded the enviroment:

icinga2: 2.11.0-1
icingaweb2: 2.7.1
director: v1.7.0
php 7.0.33

and the error is still the same

**Comment by Thomas-Gelf** [comment]
Could you please share your Icinga log lines from the time being? Do you have a single Icinga node or multiple ones?

**Comment by ChristianMoritz** [comment]
ive only got a single node..
i found the error myself.
ive got an alerting for my test host for the Group "Admins" and the notify for the jira.
cause of the inherited admin group notify which should send a seperate email notify to a another logging system the jira module creates 3 tickets for the host.

after i create an empty usergroup and inherited this group to the host now it only creates 1 ticket.

so this issue could be closed.

**Comment by Thomas-Gelf** [comment]
Thanks for letting us know!
