### ISSUE TITLE
Class 'gipfl\IcingaWeb2\CompatController' not found

### ISSUE THREAD

**Issue by NC-Yungd** [Icinga/icingaweb2-module-jira#29]
After running 'git pull' in the /usr/share/icingaweb2/modules/jira folder, I've encountered the following error in the Jira module.

I've also enable / disable from the icingacli and in the icingaweb2 and I have restarted the icinga2 services, but same error.

"Class 'gipfl\IcingaWeb2\CompatController' not found"

```
#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

Icingaweb Module shows git commit: 491ed3e040a239b277e4235e878f87150e2e4853

**Comment by NC-Yungd** [comment]
I figured it out. This module now requires the "[incubator](https://github.com/Icinga/icingaweb2-module-incubator)" module, which fixed my issue.

**Comment by loeken** [comment]
just came across the same error after installing this module, maybe link the other module as a requirement into the README.md ?
