### ISSUE TITLE
URL Link in IssueDetails Broken

### ISSUE THREAD

**Issue by cmenapace** [Icinga/icingaweb2-module-jira#31]
Hello Tom,

After Commit [RenderingHelper: create Urls in one single place](https://github.com/Icinga/icingaweb2-module-jira/commit/23fb5334e728a5f7f1f68cf9c445306fe6c1b72f)

the Links to Jira are broken, because it appends "/rest/api/2" to it

![image](https://user-images.githubusercontent.com/49369365/68745925-d3669d80-05f7-11ea-86c8-53cee78d5513.png)

Greetings

Christian

**Comment by MarcusCaepio** [comment]
I can confirm this:
Instead of https://jira.domain.de/rest/api/2/browse/issue it must be https://jira.domain.de/browse/issue
The /api/2/ part is wrong :)

**Comment by Thomas-Gelf** [comment]
Thanks @cmenapace for reporting this, thanks @MarcusCaepio for your confirmation. And sorry for breaking this, will be fixed!

**Comment by MarcusCaepio** [comment]
Hey @Thomas-Gelf 
We started to use the module a lot. Do you can say, when this issue will be fixed? As it would make work much easier and faster :)

Thanks in advance and again, great module!
Have a nice weekend.

**Comment by mrimann** [comment]
Great - thanks for merging + releasing this one!
