### ISSUE TITLE
How to set "Component/s" field when using "Service Desk" as project?

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2-module-jira#32]
Hi @Thomas-Gelf 
Version 1.0.1 looks good so far based on closed issue #28 .
Now we are struggling to set the "Component/s" field while creating an issue via the Action Url.
The Components field is not a custom field, but a system field of jira.
Any idea, how we can set it? We already tried different things both in config.ini and template.ini

![image](https://user-images.githubusercontent.com/7324088/69134936-9a776e80-0ab8-11ea-8f7f-6e9221fb9eb6.png)

Further info:
components is an array field. E.g. we tried to create a templates.ini with
`components.0.value = 13213`
where 13213 is the value ID of the component, we want.

The issue is created but the components value is not set.
We also tried to set it with a string, with or without the aposthrophes etc....

Cheers,
Marcus

**Comment by Thomas-Gelf** [comment]
@MarcusCaepio: to me your configuration looks correct. Unfortunately Jira tells me about the available Fields, but I haven't had the time to figure out how to fetch information regarding the related Data Type. Could you please open `/icingaweb2/jira/configuration/inspect`, choose your Project and then use your web browsers Developer Tools to inspect the HTML of the rightmost drop-down field? What does the entry for `components` look like?

**Comment by Thomas-Gelf** [comment]
@MarcusCaepio: eventually it's just a Case Sensitiveness problem? Did you also try to use `Components`? Honestly, I do not even know whether JIRA is case sensitive when it goes to filling JIRA custom fields.

**Comment by MarcusCaepio** [comment]
Yes, we tried different versions. In the Create Ticket Window, the module also told us, when the field was not findable or if it was not defined as array. So finding the field basically worked, but not giving this field a value. Will do the inspect part and post it here

**Comment by Thomas-Gelf** [comment]
@MarcusCaepio: got it, thanks for your patience. Could you please try this (hard-coded) patch:

```patch
--- a/library/Jira/RestApi.php
+++ b/library/Jira/RestApi.php
@@ -203,7 +203,10 @@ class RestApi
     public function createIssue($fields)
     {
         $payload = (object) [
-            'fields' => $fields
+            'fields'     => $fields,
+            'components' => [
+                (object) ['name' => 'Name Of Your Component']
+            ],
         ];
 
         $this->translateNamesToCustomFields($payload);
```

In case it works I still need to figure out how to provide this in a generic way.

**Comment by MarcusCaepio** [comment]
Will try it tomorrow. And the component's field value has to be configured in config.ini or in template.ini?

**Comment by Thomas-Gelf** [comment]
Neither, this patch hard-codes it into your source code - it's just an attempt to figure out whether it would work at all. Next require steps are:

- implementing related config setting and check parameters
- a method fetching available Components from the JIRA REST API
- providing the possibility to choose one or more of them in our web UI (for manually created issues)

To get a better understanding of those `Components`: could you give me some practical example of what you're using them for? Do I have to expect to fetch lots and lots of Components, are people using this to assign issues to Configuration Items in their CMDB? Or are these Components more like a way to bring structure into your projects, read: is this being used more like a special form of sub-projects?

Please forgive me my naive questions :-)

**Comment by MarcusCaepio** [comment]
Hi Tom,
sorry, did not have the time yesterday.
Unfortunately, the patch does not work.
![image](https://user-images.githubusercontent.com/7324088/69706251-9a4e2300-10f7-11ea-95a7-af2f5e29b1b2.png)

Of course, I will give you an example:
The component field is in Jira a predefined field for projects of the kind "Service Desk". Only projects of the kind "Service Desk" have this components field. Other projects haven't. It is supposed to divide the tickets of one project into sections/areas or how Jira calls it: components. Therefore in our IT department  we use the component field to allocate tickets of one project to our different teams within the department. E.g. has the team 'IT Admin' one component, the team 'IT Service' a different one etc. In the Icinga plugin I want to allocate an issue to the appropriate team (component) directly. If the components field exists in a project, it is an array, where pre-defined values are choosable. So e.g. a dropdown menu on the create issue would be the best way I think.

**Comment by robsy121** [comment]
@MarcusCaepio components need "name" instead of "value"
for me this works totally fine with templates.ini:
```
[my-workflow]
components.0.name = "myComp"
components.1.name = "mySecondComp"
```

@Thomas-Gelf FYI the posted JSON data looks like:
```
{
    "fields": {
        "components": [
            {
                "name": "myComp"
            },
            {
                "name": "mySecondComp"
            }
        ],
        "project": {
            "key": "EMCSD"
        },
        "issuetype": {
            "name": "Incident"
        },
        "summary": "icingatest",
        "description": "icingatest",
        "icingaKey": "BEGINexample1.comEND",
        "icingaStatus": "DOWN"
    }
}
```

In your hard-coded version above the "components" key is not nested in "fields". That's the reason why it did not work.

Thanks for the great module! 👍

**Comment by MarcusCaepio** [comment]
@robsy121 thanks for this tip. You are absolutely right.
I close the issue.
