### ISSUE TITLE
Module throwing RuntimeException over unset fields

### ISSUE THREAD

**Issue by AmierRChery** [Icinga/icingaweb2-module-jira#33]
Hey @Thomas-Gelf,  I've been trying to get this module working on my production system, but whenever I attempt to use the icingacli to send a notification it comes back telling me that "summary ", "description", "icingaKey" , and "icingaStatus" cannot be set.

I've confirmed that my permissions on Jira end are correct to the best of my ability. I'm using credentials from an admin account that's able to access all projects by default.

Attached is the command I ran and the detailed error using the ' --trace' flag. I also attached my config.ini file and screenshots of what it looks like in the web UI. 

Thank you,
Amier
![traceoutput](https://user-images.githubusercontent.com/36769615/69374197-93489000-0c73-11ea-8e78-23b72820fb53.png)
![config](https://user-images.githubusercontent.com/36769615/69374251-ace9d780-0c73-11ea-98aa-4fd9efe0fcd1.png)
![createissue](https://user-images.githubusercontent.com/36769615/69374267-b6733f80-0c73-11ea-963b-78dfb98c6a08.png)
![issues](https://user-images.githubusercontent.com/36769615/69374282-bbd08a00-0c73-11ea-87a8-fcccae1181cc.png)

**Comment by Thomas-Gelf** [comment]
@AmierRChery: admin permissions are not required at all, but you need to create two dedicated Custom Fields in JIRA first to get this integration running. Our [documentation](https://github.com/Icinga/icingaweb2-module-jira/blob/master/doc/03-Configuration.md#required-jira-custom-fields) explains how they should look like.

Cheers,
Thomas

**Comment by AmierRChery** [comment]
@Thomas-Gelf  Thank you for the prompt response and I apologize for getting back to you so late. What was weird about this issue is that I set the  custom fields in Jira as per the instructions. Attached below is the custom fields I have in the jira project i'm attempting to connect to 

Best,
Amier

![icinga-jira](https://user-images.githubusercontent.com/36769615/70245112-8d5ab080-1743-11ea-9220-9bc6f856e14b.png)

**Comment by Thomas-Gelf** [comment]
Closing this old issue. Usually this message points to either an authentication issue or fields missing on your project. In case this problem persists please do not hesitate to either create a new issue or to re-open this one.
