### ISSUE TITLE
Installation leads to open_basedir restriction Exception

### ISSUE THREAD

**Issue by mrimann** [Icinga/icingaweb2-module-jira#34]
I've installed v1.0.1 directly from Git as shown below, on a Icingaweb 2.7.3 (installed from packages), on an Ubuntu 18.04 with PHP 7.2.x (PHP-FPM)

```
cd /usr/share/icingaweb2/modules/
git clone https://github.com/Icinga/icingaweb2-module-jira jira
install -d -m 2770 -o icingaweb2 -g icingaweb2 /etc/icingaweb2/modules/jira

# add + edit config file
vi /etc/icingaweb2/modules/jira/config.ini

icingacli module enable jira
```

As soon as I enable the JIRA-Module (via CLI or in the GUI), this breaks the whole Icingaweb2 GUI to throw just the following exception:

```
Fatal error: Uncaught ErrorException: is_readable(): open_basedir restriction in effect.

File(Zend/Filter/Word/CamelCaseToDash.php) is not within the allowed path(s): (/var/www/vhosts/icinga2.internezzo.ch/httpdocs:/usr/share/icingaweb2:/usr/share/php:/etc/icingaweb2) in /usr/share/icingaweb2/library/vendor/Zend/Loader.php:162

Stack trace:
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'is_readable(): ...', '/usr/share/icin...', 162, Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Loader.php(162): is_readable('Zend/Filter/Wor...')
#2 /usr/share/icingaweb2/library/vendor/Zend/Loader/PluginLoader.php(396): Zend_Loader::isReadable('Zend/Filter/Wor...')
#3 /usr/share/icingaweb2/library/vendor/Zend/Filter/Inflector.php(515): Zend_Loader_PluginLoader->load('Word_CamelCaseT...')
#4 /usr/share/icingaweb2/library/vendor/Zend/Filter/Inflector.ph in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332
```

I don't see why this shouldn't work, since the installation path of the JIRA-module ist within the open_basedir list of paths. We have added the map module the same way, that went fine without problems.

So I guess it could be some hidden dependency to something that our system doesn't have?

Any help is well appreciated!

**Comment by mrimann** [comment]
Well, it seems like I flew through the requirements a bit too fast... After reviewing https://github.com/Icinga/icingaweb2-module-jira/blob/master/doc/03-Configuration.md again, I also installed the two referenced modules `icingaweb-module-ipl` and `icingaweb2-module-incubator` and now it looks a lot better.

I'll let the issue open - maybe the error handling in this situation could be improved to clearly state "there's some dependeny not met, giving up".

**Comment by Thomas-Gelf** [comment]
> I'll let the issue open - maybe the error handling in this situation could be improved to clearly state "there's some dependeny not met, giving up".

@mrimann: that's what it should state, yes. What makes your setup special is that you're running Icinga Web 2 with `open_basedir` restrictions in place. I'm not saying that it shouldn't work, don't worry. Just: as far as I know, we never tested that combination. Anyway, I'll let this issue open for now. I'd love to see a useful error message in such case. But please don't expect us to follow this with high priority, you're the first one I've ever met running this combination ;-)

**Comment by mrimann** [comment]
Sure, no pressure or expectation to get that in within hours or days. Just a suggesion :-)

To shed some light on **why** it is as it is:

We're operating servers for the hosting-part of a web-agency. So we roll-out a pretty generalized Nginx/PHP base-configuration to all servers that have a role with the profile "webserver". To keep things simple and unified, the Icinga2-Master host that also runs our Icingaweb2-Instance just got the profile "webserver" applied - and that's why it has a config with open_basedir applied in the PHP config by default.

As mentioned above, in the end the open_basedir restriction wasn't the problem at all - it was just that some files (ipl + incubabor modules) were missing. PHP acts strange (IMO wrong), when there is an open_basedir restriction in place and `is_readable()` or the like try to access a file that doesn't exist (independent of whether the basedir-restriction would allow to access this file when it would exist).
