### ISSUE TITLE
Add option to choose default template

### ISSUE THREAD

**Issue by mrimann** [Icinga/icingaweb2-module-jira#36]
Via the CLI, the template can be added as a CLI parameter.

But it would be cool if the config would allow to define a default template / workflow to use. In our situation this would be needed to **always** submit a certain custom field to the created issues, also for those created via the GUI.

**Comment by Thomas-Gelf** [comment]
@mrimann: do you want to set a default template, to enforce a specific template for a specific web user/role - or both?

Cheers,
Thomas

**Comment by mrimann** [comment]
For my use-case, it would be enough to just pre-select a template (and let the user choose a different one in case he/she wants to). Like this, we cannot simply forget to choose the template as it's pre-selected when creating an issue from the Icingaweb2-GUI.

For now, I don't see the need to have this different per user or role or otherwise more complicated. A simple line like the imagined examplte below in `/etc/icingaweb2/modules/jira/config.ini` would do it for me:

```
[ui]
default_template = "super-duper-template"
```

**Comment by cmenapace** [comment]
Hello @mrimann,

This works alredy, exacly like you described

add this line to the `/etc/icingaweb2/modules/jira/config.ini`

```
[ui]
default_template = "myTemplate"
```

**Comment by mrimann** [comment]
@cmenapace hehe, you're right: Tested and it works as expected. THANKS!
Strange I didn't notice that this is possible (and to be honest didn't test it, just proposed this as a new feature).
