### ISSUE TITLE
Issues created manually via UI should allow to choose a template

### ISSUE THREAD

**Issue by Ultimation** [Icinga/icingaweb2-module-jira#4]
Using latest (cdce2235b48f16cfc54c1acc048b396fea1f1046)

My template:
```cat /etc/icingaweb2/modules/jira/templates.ini
[default]
"hostname" => "${host}"
"service" => "${service}"
```
I get empty fields in jira, if I put other items I can see the fields get full of whatever is in the quotation marks that doesn't match the correct syntax. 

Digging into it a bit (createIssue in library/Jira/Web/Form/NewIssueForm.php) I can see that they are present in $params sent to the template, but the return of $template->getFilled($params)) they are blank. 

Extra info:
Latest Director (abbfa81cec84d99ea0cd2964356fb385c351f12a)
```php -v
PHP 5.4.16 (cli) (built: Apr 12 2018 19:02:01)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```
```rpm -qa | grep icinga
icingaweb2-common-2.6.1-1.el7.icinga.noarch
icingaweb2-vendor-Parsedown-2.6.1-1.el7.icinga.noarch
icinga2-ido-mysql-2.9.1-1.el7.icinga.x86_64
icinga2-common-2.9.1-1.el7.icinga.x86_64
icinga2-bin-2.9.1-1.el7.icinga.x86_64
php-Icinga-2.6.1-1.el7.icinga.noarch
icinga2-libs-2.9.1-1.el7.icinga.x86_64
icingaweb2-vendor-zf1-2.6.1-1.el7.icinga.noarch
icingaweb2-vendor-JShrink-2.6.1-1.el7.icinga.noarch
icingaweb2-vendor-dompdf-2.6.1-1.el7.icinga.noarch
icingaweb2-vendor-lessphp-2.6.1-1.el7.icinga.noarch
icingaweb2-2.6.1-1.el7.icinga.noarch
icinga2-2.9.1-1.el7.icinga.x86_64
icingacli-2.6.1-1.el7.icinga.noarch
icinga-rabbit-0.1.1-1.noarch
icingaweb2-vendor-HTMLPurifier-2.6.1-1.el7.icinga.noarch
```
CentOS Linux release 7.5.1804 (Core)

**Comment by Thomas-Gelf** [comment]
@Ultimation: templates are not required, they are optional - you should use them if you want to drive custom workflows with specific parameters. `templates.ini` is an INI file and must follow INI file syntax. If your file really looks like this...

```ini
[default]
"hostname" => "${host}"
"service" => "${service}"
```

...then you should change it to look like this:

```ini
[default]
hostname = "${host}"
service = "${service}"
```

**Comment by Ultimation** [comment]
Sorry - that's my bad, I had been trying a lot of things there. I had what you suggested originally which doesn't work. Just when writing up this ticket I forgo to revert that file to what it was meant to be

**Comment by Ultimation** [comment]
I'm doing it through the web create jira interface `/icingaweb2/jira/issues/create?`

**Comment by Thomas-Gelf** [comment]
Now I got it. Until now I only used templates in combination with automated notifications. Of course one might also want to use them when manually creating an issue. This is a bug, there should be a dropdown allowing you to choose a template in that form. Thanks for reporting this!
