### ISSUE TITLE
Module thows CommandTransportException when '--description' entry seems to be too long

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-jira#40]
The jira module seems to act wonky when '--description' is too long or has special characters which aren't escaped properly.

icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.2-1) 

OS Debian 9

'/usr/bin/icingacli' 'jira' 'send' 'problem' '--description' 'zpi: WARNING; Message: /home/icinga_rsync/sync/logs/psscronos/search-messagetab.protocol-2020-01-13-00-23-18 2020.01.13 00:23:18;zpi;WARN;Wert:   15\ncheck_log status:\n\n/home/icinga_rsync/sync/logs/psscronos/search-messagetab.protocol-2020-01-13-00-23-18 2020.01.13 00:23:18;zpi;WARN;Wert:       15\n/home/icinga_rsync/sync/logs/psscronos/search-messagetab.protocol-2020-01-13-00-18-18 2020.01.13 00:18:18;zpi;WARN;Wert:    15\n\n' '--host' 'Anonymous' '--issuetype' 'Incident' '--project' 'ITSM' '--service' 'anonymous' '--state' 'WARNING' '--summary' 'Anonymous on anonymous is WARNING'

Icinga\Module\Monitoring\Exception\CommandTransportException in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Command/Transport/ApiCommandTransport.php:234 with message: Can't send external Icinga command: 409 Service Anonymous!anonymous is OK.

Icinga 2 API: Can't send external Icinga command: 409 Service Anonymous!anonymous is OK.

**Comment by Thomas-Gelf** [comment]
This error appears when creating an issue for a Service or Host in an OK state. The Command tries to acknowledge the Icinga Problem, and Icinga refuses to do so. The issue has been created anyway.

Therefore, closing this as a non-issue.
