### ISSUE TITLE
Fill in Organizations in ServiceDesk Project is not possible

### ISSUE THREAD

**Issue by bahrpatrick** [Icinga/icingaweb2-module-jira#43]
Hi, 

it would be nice if it´s possible to add a organization to a new created ticket via this module.
At the moment it seems like it´s not possible to fill in a number to a field, but this is required for the "organizations" field.

The following issue occurs:

"Operation value must be a number at array index 0" 

Not sure if I only have the wrong configuration or it´s simply not possible.

Thanks for your help and by the way nice module!

**Comment by mkayontour** [comment]
Have you tried the following:
[section]
organizations.0.name = "orgname" 

Have a look at the response in the following ticket: #32

**Comment by bahrpatrick** [comment]
Hi @mkayontour ,

thanks for your answer, yes I´ve already tried this and it didn´t work out... :(

**Comment by mkayontour** [comment]
Have you tried using the organization ID? 

`organizations.0.value = 1234 `

For example, at our components field I can use name or value and the value must then be the internal ID of the component.

**Comment by bahrpatrick** [comment]
Yes i did but then it always shows up the same error. 
I tried all of these combinations, but it seems like it´s not possible to use a number as value or name. I found an article, that it´s requried to use the ID for the Organizations field...

Thanks for your help

**Comment by TheAaske** [comment]
Did you manage to find a solution to this? have the exact same problem.
