### ISSUE TITLE
 ErrorException in /usr/share/icingaweb2/modules/jira/library/Jira/RestApi.php:400 with message: A non well formed numeric value encountered

### ISSUE THREAD

**Issue by Nicknew404** [Icinga/icingaweb2-module-jira#52]
if we connect via Icingacli and from there send the request to Jira via Rest Api with:
icingacli jira send problem --host test.test.dev --project TEST --issuetype Incident --state DOWN --description "Test Incident" --summary 'Test'

then we get the error message:
ERROR: ErrorException in /usr/share/icingaweb2/modules/jira/library/Jira/RestApi.php:400 with message: A non well formed numeric value encountered

Does anyone know this error?

**Comment by log1-c** [comment]
Did you solve the problem?
Have you checked if there is a problem with the authentication?
https://github.com/Icinga/icingaweb2-module-jira/issues/49 had the same error message because of a problem with the auth token
