### ISSUE TITLE
Don't show inspect tab by default

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-jira#65]
Remove default project "ITSM" so that project is configurable.

Module Version: v1.1.0

**Comment by raviks789** [comment]
@mwaldmueller the inspect tab will be removed as this is used for testing purpose only refer #91. So this issue becomes obsolete.

**Comment by mwaldmueller** [comment]
I think this is not only related to the inspect tab, it's a generic issue. The project 'ITSM' is static in /library/Jira/Web/Form/TemplateForm.php.

**Comment by raviks789** [comment]
> I think this is not only related to the inspect tab, it's a generic issue. The project 'ITSM' is static in /library/Jira/Web/Form/TemplateForm.php.

`TemplateForm` is used only in the inspect tab. Hence, when the  inspecttab is removed the issue automatically becomes obsolete.
